--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/MadeAja/NichiJoinLocation
build-by-default: true
branches:
- master
projects:
  NichiJoinLocation:
    path: "MadeAja\joinLocation\Main"
...
